### PR TITLE
Add code for exporting translations as PRs

### PR DESCRIPTION
**Pull request by forslund**
This is the script for extracting po files and generating PR's for language updates. Currently it doesn't download and extract the files from pootle. It expects that to have been done already and that the files are extracted into the current work directory.

### CODE REVIEW

**Comment by KathyReid** [comment]
Thanks so much for this, @forslund. 

A few comments; 

On [this line](https://github.com/MycroftAI/mycroft-translate/blob/25f026ca3f077f24251f7fe48e848116c28a30ed/automations/extract/generate_prs.py#L60), it is mentioned that getting the list of language files is "todo". There is a way in Pootle, if you are in the Pootle `venv` to get a list of languages if this helps. 

```
(env) root@translate-dev-00:~/pootle-webroot# pootle list_languages
ca
cs
cy
de
en
en_GB
es
fil
fr
ga
gd
haw
hi
id
is
it
ja
mi
nl
nn
pl
pt
pt_BR
ro
ru
sco
sv
vi
zh_CN
```

On [this line](https://github.com/MycroftAI/mycroft-translate/blob/25f026ca3f077f24251f7fe48e848116c28a30ed/automations/extract/generate_prs.py#L124) a `dict` of languages is defined, but only three languages are defined. Does that mean that the extract script only currently works on those languages? If so, that's OK, it's just useful to know so I can communicate it. 

Is it safe for me to put this script under `cron.daily`?

Thanks again @forslund !

**Comment by forslund** [comment]
Since this PR I've added a couple of new languages and done some fixes. I'll update the PR.

**Review by KathyReid — COMMENTED** [review]
This looks really good to me @forslund; a couple of questions; 

* does it make sense only to have a few languages at the moment? Or should we get the languages from the Pootle `list_languages` command? 
* when this script is deployed it would likely be called by `cron` in some form. Does it need a `bash` wrapper at all? 

Otherwise, this reads very well, no bugs or errors that I could find with just a read through.

**Comment by forslund** [comment]
If I recall correctly the script has a shebang. so it could be called directly. Currently it doesn't download and unpack the languages. so that might have to be done in a bash script. Oh and the github access key needs to be set as an enviroment variable in the cronjob

Currently I've added languages that are more than 50% translated for processing, getting the complete list would be better but we need a dict to translate pootle-lang-codes -> mycroft-lang-codes

**Comment by KathyReid** [comment]
Apologies @forslund I forgot to look at this PR again. 
Should I merge this?

**Comment by forslund** [comment]
It's the basic functionallity and it might be good to have in here so I can continue development using this repo.

**Comment by KathyReid** [comment]
Versagod ;-)

**Pull request merged**
